### PR TITLE
verify: Support digest-based image reference

### LINKED ISSUE #906: `verify` always fails with 404 when using image digest, even if the image actually exists
reproducing code is in here: https://github.com/mi-wada/reproduce/tree/main/kayac/ecspresso/verify-failed-with-image-digest

## Issue

When specifying the Container image version using an [image digest](https://docs.docker.com/dhi/core-concepts/digests/) in an ECS task definition, such as `nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42`, the `ecspresso verify` command will fail with a 404 Not Found error, even if the image exists in the remote registry.

```console
$ ecspresso verify
2025-11-23T19:14:12.196+09:00 [INFO] ecspresso version: v2.6.4
2025-11-23T19:14:12.199+09:00 [INFO] [example/example] executionRoleArn is not set. Continue to verify with current session.
2025-11-23T19:14:12.199+09:00 [INFO] [example/example] Starting verify
      Image[nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42]
      --> [NG] 404 Not Found
    ContainerDefinition[]
    --> [NG] verify Image[nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42] failed: 404 Not Found
  TaskDefinition
  --> [NG] verify ContainerDefinition[] failed: verify Image[nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42] failed: 404 Not Found
2025-11-23T19:14:12.753+09:00 [ERROR] FAILED. verify TaskDefinition failed: verify ContainerDefinition[] failed: verify Image[nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42] failed: 404 Not Found
```

minimal reproduce `ecs-task-def.json`:
```json
{
  "containerDefinitions": [
    {
      "image": "nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42"
    }
  ]
}
```

As follows, `nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42` actually exists in the remote registry.

```console
$ docker pull nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
docker.io/library/nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42: Pulling from library/nginx
b89cf3ec7a3e: Pull complete
2254fb813b11: Pull complete
40b6fc5618c6: Pull complete
bb8ecb62799c: Pull complete
cc57e8335c98: Pull complete
cf9a807fe41d: Pull complete
88770be1d442: Pull complete
Digest: sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
Status: Downloaded newer image for nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
docker.io/library/nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
```

## Maybe cause

The probable cause of this issue is that `ecspresso verify` does not support specifying an image using its digest. `ecspresso verify` currently only supports the tag-based format (e.g., `nginx:latest`).

<https://github.com/kayac/ecspresso/blob/63ff2bd5553911be1da80b26914453c037c4c26b/verify.go#L644>

### PR DESCRIPTION
**Pull request by mi-wada**
close: https://github.com/kayac/ecspresso/issues/906

In `ecspresso verify`, support [digest-based image reference](https://docs.docker.com/dhi/core-concepts/digests/) in task
definition file like a:

```json
{
  # ...
  "containerDefinitions": [
    {
      "image": "nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42"
    }
  ]
  # ...
}
```

This change enables correct image existence checks and other operations even when using digest-based image references. Previously, the `verify` command only supported tag-based image references (e.g., `debian:latest`), so it would unconditionally return a 404 when using digest-based image references.

I confirmed that it works on my local:
```console
kayac/ecspresso/verify-failed-with-image-digest (main)🔥 on ☁️  (ap-northeast-1)
$ /Users/wada.mitsuaki/ghq/github.com/mi-wada/ecspresso/ecspresso verify --debug
2025-11-25T12:55:15.814+09:00 [INFO] ecspresso version:
2025-11-25T12:55:15.816+09:00 [DEBUG] [example/main] config file path: ecspresso.yml
2025-11-25T12:55:15.816+09:00 [DEBUG] [example/main] timeout: 10m0s
2025-11-25T12:55:15.817+09:00 [DEBUG] [example/main] dispatching subcommand: verify
2025-11-25T12:55:15.817+09:00 [INFO] [example/main] executionRoleArn is not set. Continue to verify with current session.
2025-11-25T12:55:15.817+09:00 [INFO] [example/main] Starting verify
2025-11-25T12:55:15.817+09:00 [DEBUG] [example/main] VERIFY Registry Image nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
2025-11-25T12:55:15.817+09:00 [DEBUG] [example/main] imageName=nginx tagOrDigest=sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
      Image[nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42]
      --> [OK]
    ContainerDefinition[]
    --> [OK]
  TaskDefinition
  --> [OK]
  ServiceDefinition
  --> [SKIP] no ServiceDefinition
  Cluster
  --> [OK]
2025-11-25T12:55:17.310+09:00 [INFO] [example/main] Verify OK!

kayac/ecspresso/verify-failed-with-image-digest (main)🔥 on ☁️  (ap-northeast-1)
$ cat ecspresso.yml
region: "ap-northeast-1"
cluster: main
service: example
task_definition: ecs-task-def.json
timeout: "10m0s"

kayac/ecspresso/verify-failed-with-image-digest (main)🔥 on ☁️  (ap-northeast-1)
$ cat ecs-task-def.json
{
  "containerDefinitions": [
    {
      "image": "nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42"
    }
  ]
}
```

### CODE REVIEW

File: registry/client.go [hunk 1]
```diff
@@ -104,8 +104,8 @@ func (c *Repository) login(ctx context.Context, endpoint, service, scope string)
 	return nil
 }
 
-func (c *Repository) fetchManifests(ctx context.Context, method, tag string) (*http.Response, error) {
```
Comment (mi-wada) [inline registry/client.go:107]: I read several documents, but there doesn't seem to be an official word for "tag or digest," so I named it "tagOrDigest" straightforwardly.
- https://github.com/opencontainers/distribution-spec/blob/e612a6e1e1bc717f9fa7e1feb4f05c8b6568754a/spec.md
- https://github.com/distribution/reference/blob/727f80d42224f6696b8e1ad16b06aadf2c6b833b/reference.go#L6

File: registry/client_test.go [hunk 2]
```diff
@@ -11,76 +12,95 @@ import (
...
+	{image: "gcr.io/kaniko-project/executor", tagOrDigest: "xxx", arch: "amd64", os: "linux"},
+	{image: "ghcr.io/github/super-linter", tagOrDigest: "xxx", arch: "amd64", os: "linux"},
+	{image: "mcr.microsoft.com/windows/servercore/iis", tagOrDigest: "xxx", arch: "amd64", os: "windows"},
+	{image: "xxx", tagOrDigest: "xxx", arch: "xxx", os: "xxx"},
 }
 
 func TestImages(t *testing.T) {
 	for _, c := range testImages {
-		t.Logf("testing %s:%s", c.image, c.tag)
+		var fullImage string
```
Comment (mi-wada) [inline registry/client_test.go:52]: I thought it would be easier to understand if the tests were written inline, so I haven't created helper functions. If you have any opinions, I will revise it.

File: verify.go [hunk 3]
```diff
@@ -641,23 +641,27 @@ func (d *App) verifyECRImage(ctx context.Context, image, region string) error {
 }
 
 func (d *App) verifyRegistryImage(ctx context.Context, image, user, password string) error {
-	rr := strings.SplitN(image, ":", 2)
-	image = rr[0]
-	var tag string
-	if len(rr) == 1 {
-		tag = "latest"
+	var imageName string
```
Comment (mi-wada) [inline verify.go:644]: In Go package [distribution/reference](https://github.com/distribution/reference), the part before tag/digest is called name, so I named that part `imageName`. If you have any opinions, I will revise it.

https://github.com/distribution/reference/blob/727f80d42224f6696b8e1ad16b06aadf2c6b833b/reference.go#L6

**Comment by mi-wada** [comment]
Tested after 0fa52a9c2fd068347fa356ec3962be9b557e9c8e

---

tag-based
```console
kayac/ecspresso/verify-failed-with-image-digest (main)🔥 on ☁️  (ap-northeast-1) 
$ /Users/wada.mitsuaki/ghq/github.com/mi-wada/ecspresso/ecspresso verify --debug
2025-11-25T14:01:29.915+09:00 [INFO] ecspresso version: 
2025-11-25T14:01:29.917+09:00 [DEBUG] [example/main] config file path: ecspresso.yml
2025-11-25T14:01:29.918+09:00 [DEBUG] [example/main] timeout: 10m0s
2025-11-25T14:01:29.918+09:00 [DEBUG] [example/main] dispatching subcommand: verify
2025-11-25T14:01:29.918+09:00 [INFO] [example/main] executionRoleArn is not set. Continue to verify with current session.
2025-11-25T14:01:29.918+09:00 [INFO] [example/main] Starting verify
2025-11-25T14:01:29.918+09:00 [DEBUG] [example/main] VERIFY Registry Image registry-1.docker.io:443/library/nginx:latest
2025-11-25T14:01:29.918+09:00 [DEBUG] [example/main] imageName=registry-1.docker.io:443/library/nginx tagOrDigest=latest
      Image[registry-1.docker.io:443/library/nginx:latest]
      --> [OK]
    ContainerDefinition[]
    --> [OK]
  TaskDefinition
  --> [OK]
  ServiceDefinition
  --> [SKIP] no ServiceDefinition
  Cluster
  --> [OK]
2025-11-25T14:01:31.482+09:00 [INFO] [example/main] Verify OK!

kayac/ecspresso/verify-failed-with-image-digest (main)🔥 on ☁️  (ap-northeast-1) 
$ cat ecs-task-def.json
{
  "containerDefinitions": [
    {
      "image": "registry-1.docker.io:443/library/nginx:latest"
    }
  ]
}
```

---

digest-based
```console
kayac/ecspresso/verify-failed-with-image-digest (main)🔥 on ☁️  (ap-northeast-1) 
$ /Users/wada.mitsuaki/ghq/github.com/mi-wada/ecspresso/ecspresso verify --debug
2025-11-25T14:02:19.568+09:00 [INFO] ecspresso version: 
2025-11-25T14:02:19.568+09:00 [DEBUG] [example/main] config file path: ecspresso.yml
2025-11-25T14:02:19.568+09:00 [DEBUG] [example/main] timeout: 10m0s
2025-11-25T14:02:19.568+09:00 [DEBUG] [example/main] dispatching subcommand: verify
2025-11-25T14:02:19.568+09:00 [INFO] [example/main] executionRoleArn is not set. Continue to verify with current session.
2025-11-25T14:02:19.568+09:00 [INFO] [example/main] Starting verify
2025-11-25T14:02:19.568+09:00 [DEBUG] [example/main] VERIFY Registry Image registry-1.docker.io:443/library/nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
2025-11-25T14:02:19.568+09:00 [DEBUG] [example/main] imageName=registry-1.docker.io:443/library/nginx tagOrDigest=sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
      Image[registry-1.docker.io:443/library/nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42]
      --> [OK]
    ContainerDefinition[]
    --> [OK]
  TaskDefinition
  --> [OK]
  ServiceDefinition
  --> [SKIP] no ServiceDefinition
  Cluster
  --> [OK]
2025-11-25T14:02:21.056+09:00 [INFO] [example/main] Verify OK!

kayac/ecspresso/verify-failed-with-image-digest (main)🔥 on ☁️  (ap-northeast-1) 
$ cat ecs-task-def.json
{
  "containerDefinitions": [
    {
      "image": "registry-1.docker.io:443/library/nginx@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42"
    }
  ]
}
```

File: verify.go [hunk 4]
```diff
@@ -641,23 +641,27 @@ func (d *App) verifyECRImage(ctx context.Context, image, region string) error {
...
+		imageName = rr[0]
+		tagOrDigest = rr[1]
+	} else if rr := strings.SplitN(image, ":", 2); len(rr) == 2 {
+		imageName = rr[0]
+		tagOrDigest = rr[1]
 	} else {
-		tag = rr[1]
+		imageName = image
+		tagOrDigest = "latest"
 	}
```
[the remark this answers is not in the document]
Comment (mi-wada) [reply verify.go]: fixed at 0fa52a9c2fd068347fa356ec3962be9b557e9c8e

**Comment by fujiwara** [comment]
@mi-wada Great work! I've confirmed `ecspresso verify` works well. Thank you!!
